package com.lingzerg.gamecenter.proto;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ActionBroadcastPro.proto

public final class ActionBroadcastPro {
  private ActionBroadcastPro() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ActionBroadcastProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 playerId = 1;
    /**
     * <code>required int32 playerId = 1;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>required int32 playerId = 1;</code>
     */
    int getPlayerId();

    // required int32 seat = 2;
    /**
     * <code>required int32 seat = 2;</code>
     */
    boolean hasSeat();
    /**
     * <code>required int32 seat = 2;</code>
     */
    int getSeat();

    // required int32 act = 3;
    /**
     * <code>required int32 act = 3;</code>
     *
     * <pre>
     *1=让牌，2=跟注，3=加注，4=all in，5=弃牌
     * </pre>
     */
    boolean hasAct();
    /**
     * <code>required int32 act = 3;</code>
     *
     * <pre>
     *1=让牌，2=跟注，3=加注，4=all in，5=弃牌
     * </pre>
     */
    int getAct();

    // required int32 ante = 4;
    /**
     * <code>required int32 ante = 4;</code>
     *
     * <pre>
     *金额
     * </pre>
     */
    boolean hasAnte();
    /**
     * <code>required int32 ante = 4;</code>
     *
     * <pre>
     *金额
     * </pre>
     */
    int getAnte();
  }
  /**
   * Protobuf type {@code ActionBroadcastProto}
   */
  public static final class ActionBroadcastProto extends
      com.google.protobuf.GeneratedMessage
      implements ActionBroadcastProtoOrBuilder {
    // Use ActionBroadcastProto.newBuilder() to construct.
    private ActionBroadcastProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ActionBroadcastProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ActionBroadcastProto defaultInstance;
    public static ActionBroadcastProto getDefaultInstance() {
      return defaultInstance;
    }

    public ActionBroadcastProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ActionBroadcastProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              seat_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              act_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              ante_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ActionBroadcastPro.internal_static_ActionBroadcastProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ActionBroadcastPro.internal_static_ActionBroadcastProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ActionBroadcastPro.ActionBroadcastProto.class, ActionBroadcastPro.ActionBroadcastProto.Builder.class);
    }

    public static com.google.protobuf.Parser<ActionBroadcastProto> PARSER =
        new com.google.protobuf.AbstractParser<ActionBroadcastProto>() {
      public ActionBroadcastProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ActionBroadcastProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ActionBroadcastProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 playerId = 1;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private int playerId_;
    /**
     * <code>required int32 playerId = 1;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 playerId = 1;</code>
     */
    public int getPlayerId() {
      return playerId_;
    }

    // required int32 seat = 2;
    public static final int SEAT_FIELD_NUMBER = 2;
    private int seat_;
    /**
     * <code>required int32 seat = 2;</code>
     */
    public boolean hasSeat() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 seat = 2;</code>
     */
    public int getSeat() {
      return seat_;
    }

    // required int32 act = 3;
    public static final int ACT_FIELD_NUMBER = 3;
    private int act_;
    /**
     * <code>required int32 act = 3;</code>
     *
     * <pre>
     *1=让牌，2=跟注，3=加注，4=all in，5=弃牌
     * </pre>
     */
    public boolean hasAct() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 act = 3;</code>
     *
     * <pre>
     *1=让牌，2=跟注，3=加注，4=all in，5=弃牌
     * </pre>
     */
    public int getAct() {
      return act_;
    }

    // required int32 ante = 4;
    public static final int ANTE_FIELD_NUMBER = 4;
    private int ante_;
    /**
     * <code>required int32 ante = 4;</code>
     *
     * <pre>
     *金额
     * </pre>
     */
    public boolean hasAnte() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 ante = 4;</code>
     *
     * <pre>
     *金额
     * </pre>
     */
    public int getAnte() {
      return ante_;
    }

    private void initFields() {
      playerId_ = 0;
      seat_ = 0;
      act_ = 0;
      ante_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSeat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAct()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAnte()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, seat_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, act_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, ante_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, seat_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, act_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, ante_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ActionBroadcastPro.ActionBroadcastProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ActionBroadcastPro.ActionBroadcastProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ActionBroadcastPro.ActionBroadcastProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ActionBroadcastPro.ActionBroadcastProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ActionBroadcastPro.ActionBroadcastProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ActionBroadcastPro.ActionBroadcastProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ActionBroadcastPro.ActionBroadcastProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ActionBroadcastPro.ActionBroadcastProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ActionBroadcastPro.ActionBroadcastProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ActionBroadcastPro.ActionBroadcastProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ActionBroadcastPro.ActionBroadcastProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ActionBroadcastProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ActionBroadcastPro.ActionBroadcastProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ActionBroadcastPro.internal_static_ActionBroadcastProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ActionBroadcastPro.internal_static_ActionBroadcastProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ActionBroadcastPro.ActionBroadcastProto.class, ActionBroadcastPro.ActionBroadcastProto.Builder.class);
      }

      // Construct using ActionBroadcastPro.ActionBroadcastProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        seat_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        act_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        ante_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ActionBroadcastPro.internal_static_ActionBroadcastProto_descriptor;
      }

      public ActionBroadcastPro.ActionBroadcastProto getDefaultInstanceForType() {
        return ActionBroadcastPro.ActionBroadcastProto.getDefaultInstance();
      }

      public ActionBroadcastPro.ActionBroadcastProto build() {
        ActionBroadcastPro.ActionBroadcastProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ActionBroadcastPro.ActionBroadcastProto buildPartial() {
        ActionBroadcastPro.ActionBroadcastProto result = new ActionBroadcastPro.ActionBroadcastProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.seat_ = seat_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.act_ = act_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ante_ = ante_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ActionBroadcastPro.ActionBroadcastProto) {
          return mergeFrom((ActionBroadcastPro.ActionBroadcastProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ActionBroadcastPro.ActionBroadcastProto other) {
        if (other == ActionBroadcastPro.ActionBroadcastProto.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasSeat()) {
          setSeat(other.getSeat());
        }
        if (other.hasAct()) {
          setAct(other.getAct());
        }
        if (other.hasAnte()) {
          setAnte(other.getAnte());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPlayerId()) {
          
          return false;
        }
        if (!hasSeat()) {
          
          return false;
        }
        if (!hasAct()) {
          
          return false;
        }
        if (!hasAnte()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ActionBroadcastPro.ActionBroadcastProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ActionBroadcastPro.ActionBroadcastProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 playerId = 1;
      private int playerId_ ;
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0;
        onChanged();
        return this;
      }

      // required int32 seat = 2;
      private int seat_ ;
      /**
       * <code>required int32 seat = 2;</code>
       */
      public boolean hasSeat() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 seat = 2;</code>
       */
      public int getSeat() {
        return seat_;
      }
      /**
       * <code>required int32 seat = 2;</code>
       */
      public Builder setSeat(int value) {
        bitField0_ |= 0x00000002;
        seat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 seat = 2;</code>
       */
      public Builder clearSeat() {
        bitField0_ = (bitField0_ & ~0x00000002);
        seat_ = 0;
        onChanged();
        return this;
      }

      // required int32 act = 3;
      private int act_ ;
      /**
       * <code>required int32 act = 3;</code>
       *
       * <pre>
       *1=让牌，2=跟注，3=加注，4=all in，5=弃牌
       * </pre>
       */
      public boolean hasAct() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 act = 3;</code>
       *
       * <pre>
       *1=让牌，2=跟注，3=加注，4=all in，5=弃牌
       * </pre>
       */
      public int getAct() {
        return act_;
      }
      /**
       * <code>required int32 act = 3;</code>
       *
       * <pre>
       *1=让牌，2=跟注，3=加注，4=all in，5=弃牌
       * </pre>
       */
      public Builder setAct(int value) {
        bitField0_ |= 0x00000004;
        act_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 act = 3;</code>
       *
       * <pre>
       *1=让牌，2=跟注，3=加注，4=all in，5=弃牌
       * </pre>
       */
      public Builder clearAct() {
        bitField0_ = (bitField0_ & ~0x00000004);
        act_ = 0;
        onChanged();
        return this;
      }

      // required int32 ante = 4;
      private int ante_ ;
      /**
       * <code>required int32 ante = 4;</code>
       *
       * <pre>
       *金额
       * </pre>
       */
      public boolean hasAnte() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 ante = 4;</code>
       *
       * <pre>
       *金额
       * </pre>
       */
      public int getAnte() {
        return ante_;
      }
      /**
       * <code>required int32 ante = 4;</code>
       *
       * <pre>
       *金额
       * </pre>
       */
      public Builder setAnte(int value) {
        bitField0_ |= 0x00000008;
        ante_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ante = 4;</code>
       *
       * <pre>
       *金额
       * </pre>
       */
      public Builder clearAnte() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ante_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ActionBroadcastProto)
    }

    static {
      defaultInstance = new ActionBroadcastProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ActionBroadcastProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ActionBroadcastProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ActionBroadcastProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ActionBroadcastPro.proto\"Q\n\024ActionBroa" +
      "dcastProto\022\020\n\010playerId\030\001 \002(\005\022\014\n\004seat\030\002 \002" +
      "(\005\022\013\n\003act\030\003 \002(\005\022\014\n\004ante\030\004 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ActionBroadcastProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ActionBroadcastProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ActionBroadcastProto_descriptor,
              new java.lang.String[] { "PlayerId", "Seat", "Act", "Ante", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
