package com.lingzerg.gamecenter.proto;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KnockoutBroadcastPro.proto

public final class KnockoutBroadcastPro {
  private KnockoutBroadcastPro() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface KnockoutBroadcastProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 playerId = 1;
    /**
     * <code>required int32 playerId = 1;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>required int32 playerId = 1;</code>
     */
    int getPlayerId();

    // required int32 seat = 2;
    /**
     * <code>required int32 seat = 2;</code>
     */
    boolean hasSeat();
    /**
     * <code>required int32 seat = 2;</code>
     */
    int getSeat();
  }
  /**
   * Protobuf type {@code KnockoutBroadcastProto}
   */
  public static final class KnockoutBroadcastProto extends
      com.google.protobuf.GeneratedMessage
      implements KnockoutBroadcastProtoOrBuilder {
    // Use KnockoutBroadcastProto.newBuilder() to construct.
    private KnockoutBroadcastProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KnockoutBroadcastProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KnockoutBroadcastProto defaultInstance;
    public static KnockoutBroadcastProto getDefaultInstance() {
      return defaultInstance;
    }

    public KnockoutBroadcastProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KnockoutBroadcastProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              seat_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return KnockoutBroadcastPro.internal_static_KnockoutBroadcastProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return KnockoutBroadcastPro.internal_static_KnockoutBroadcastProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              KnockoutBroadcastPro.KnockoutBroadcastProto.class, KnockoutBroadcastPro.KnockoutBroadcastProto.Builder.class);
    }

    public static com.google.protobuf.Parser<KnockoutBroadcastProto> PARSER =
        new com.google.protobuf.AbstractParser<KnockoutBroadcastProto>() {
      public KnockoutBroadcastProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KnockoutBroadcastProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KnockoutBroadcastProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 playerId = 1;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private int playerId_;
    /**
     * <code>required int32 playerId = 1;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 playerId = 1;</code>
     */
    public int getPlayerId() {
      return playerId_;
    }

    // required int32 seat = 2;
    public static final int SEAT_FIELD_NUMBER = 2;
    private int seat_;
    /**
     * <code>required int32 seat = 2;</code>
     */
    public boolean hasSeat() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 seat = 2;</code>
     */
    public int getSeat() {
      return seat_;
    }

    private void initFields() {
      playerId_ = 0;
      seat_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSeat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, seat_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, seat_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static KnockoutBroadcastPro.KnockoutBroadcastProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static KnockoutBroadcastPro.KnockoutBroadcastProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static KnockoutBroadcastPro.KnockoutBroadcastProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static KnockoutBroadcastPro.KnockoutBroadcastProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static KnockoutBroadcastPro.KnockoutBroadcastProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static KnockoutBroadcastPro.KnockoutBroadcastProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static KnockoutBroadcastPro.KnockoutBroadcastProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static KnockoutBroadcastPro.KnockoutBroadcastProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static KnockoutBroadcastPro.KnockoutBroadcastProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static KnockoutBroadcastPro.KnockoutBroadcastProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(KnockoutBroadcastPro.KnockoutBroadcastProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code KnockoutBroadcastProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements KnockoutBroadcastPro.KnockoutBroadcastProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return KnockoutBroadcastPro.internal_static_KnockoutBroadcastProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return KnockoutBroadcastPro.internal_static_KnockoutBroadcastProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                KnockoutBroadcastPro.KnockoutBroadcastProto.class, KnockoutBroadcastPro.KnockoutBroadcastProto.Builder.class);
      }

      // Construct using KnockoutBroadcastPro.KnockoutBroadcastProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        seat_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return KnockoutBroadcastPro.internal_static_KnockoutBroadcastProto_descriptor;
      }

      public KnockoutBroadcastPro.KnockoutBroadcastProto getDefaultInstanceForType() {
        return KnockoutBroadcastPro.KnockoutBroadcastProto.getDefaultInstance();
      }

      public KnockoutBroadcastPro.KnockoutBroadcastProto build() {
        KnockoutBroadcastPro.KnockoutBroadcastProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public KnockoutBroadcastPro.KnockoutBroadcastProto buildPartial() {
        KnockoutBroadcastPro.KnockoutBroadcastProto result = new KnockoutBroadcastPro.KnockoutBroadcastProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.seat_ = seat_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof KnockoutBroadcastPro.KnockoutBroadcastProto) {
          return mergeFrom((KnockoutBroadcastPro.KnockoutBroadcastProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(KnockoutBroadcastPro.KnockoutBroadcastProto other) {
        if (other == KnockoutBroadcastPro.KnockoutBroadcastProto.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasSeat()) {
          setSeat(other.getSeat());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPlayerId()) {
          
          return false;
        }
        if (!hasSeat()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        KnockoutBroadcastPro.KnockoutBroadcastProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (KnockoutBroadcastPro.KnockoutBroadcastProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 playerId = 1;
      private int playerId_ ;
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0;
        onChanged();
        return this;
      }

      // required int32 seat = 2;
      private int seat_ ;
      /**
       * <code>required int32 seat = 2;</code>
       */
      public boolean hasSeat() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 seat = 2;</code>
       */
      public int getSeat() {
        return seat_;
      }
      /**
       * <code>required int32 seat = 2;</code>
       */
      public Builder setSeat(int value) {
        bitField0_ |= 0x00000002;
        seat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 seat = 2;</code>
       */
      public Builder clearSeat() {
        bitField0_ = (bitField0_ & ~0x00000002);
        seat_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:KnockoutBroadcastProto)
    }

    static {
      defaultInstance = new KnockoutBroadcastProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:KnockoutBroadcastProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_KnockoutBroadcastProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_KnockoutBroadcastProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032KnockoutBroadcastPro.proto\"8\n\026Knockout" +
      "BroadcastProto\022\020\n\010playerId\030\001 \002(\005\022\014\n\004seat" +
      "\030\002 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_KnockoutBroadcastProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_KnockoutBroadcastProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_KnockoutBroadcastProto_descriptor,
              new java.lang.String[] { "PlayerId", "Seat", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
