package com.lingzerg.gamecenter.proto;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResultPro.proto

public final class ResultPro {
  private ResultPro() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResultProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .ResultProto.Winner winnerList = 1;
    /**
     * <code>repeated .ResultProto.Winner winnerList = 1;</code>
     */
    java.util.List<ResultPro.ResultProto.Winner> 
        getWinnerListList();
    /**
     * <code>repeated .ResultProto.Winner winnerList = 1;</code>
     */
    ResultPro.ResultProto.Winner getWinnerList(int index);
    /**
     * <code>repeated .ResultProto.Winner winnerList = 1;</code>
     */
    int getWinnerListCount();
    /**
     * <code>repeated .ResultProto.Winner winnerList = 1;</code>
     */
    java.util.List<? extends ResultPro.ResultProto.WinnerOrBuilder> 
        getWinnerListOrBuilderList();
    /**
     * <code>repeated .ResultProto.Winner winnerList = 1;</code>
     */
    ResultPro.ResultProto.WinnerOrBuilder getWinnerListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ResultProto}
   */
  public static final class ResultProto extends
      com.google.protobuf.GeneratedMessage
      implements ResultProtoOrBuilder {
    // Use ResultProto.newBuilder() to construct.
    private ResultProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResultProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResultProto defaultInstance;
    public static ResultProto getDefaultInstance() {
      return defaultInstance;
    }

    public ResultProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResultProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                winnerList_ = new java.util.ArrayList<ResultPro.ResultProto.Winner>();
                mutable_bitField0_ |= 0x00000001;
              }
              winnerList_.add(input.readMessage(ResultPro.ResultProto.Winner.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          winnerList_ = java.util.Collections.unmodifiableList(winnerList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ResultPro.internal_static_ResultProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ResultPro.internal_static_ResultProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResultPro.ResultProto.class, ResultPro.ResultProto.Builder.class);
    }

    public static com.google.protobuf.Parser<ResultProto> PARSER =
        new com.google.protobuf.AbstractParser<ResultProto>() {
      public ResultProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResultProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResultProto> getParserForType() {
      return PARSER;
    }

    public interface WinnerOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required int32 playerId = 1;
      /**
       * <code>required int32 playerId = 1;</code>
       */
      boolean hasPlayerId();
      /**
       * <code>required int32 playerId = 1;</code>
       */
      int getPlayerId();

      // required int32 seat = 2;
      /**
       * <code>required int32 seat = 2;</code>
       *
       * <pre>
       *座号
       * </pre>
       */
      boolean hasSeat();
      /**
       * <code>required int32 seat = 2;</code>
       *
       * <pre>
       *座号
       * </pre>
       */
      int getSeat();

      // optional string title = 3;
      /**
       * <code>optional string title = 3;</code>
       *
       * <pre>
       *牌型名称
       * </pre>
       */
      boolean hasTitle();
      /**
       * <code>optional string title = 3;</code>
       *
       * <pre>
       *牌型名称
       * </pre>
       */
      java.lang.String getTitle();
      /**
       * <code>optional string title = 3;</code>
       *
       * <pre>
       *牌型名称
       * </pre>
       */
      com.google.protobuf.ByteString
          getTitleBytes();

      // optional int32 type = 4;
      /**
       * <code>optional int32 type = 4;</code>
       *
       * <pre>
       *牌型
       * </pre>
       */
      boolean hasType();
      /**
       * <code>optional int32 type = 4;</code>
       *
       * <pre>
       *牌型
       * </pre>
       */
      int getType();

      // optional bytes holecards = 5;
      /**
       * <code>optional bytes holecards = 5;</code>
       */
      boolean hasHolecards();
      /**
       * <code>optional bytes holecards = 5;</code>
       */
      com.google.protobuf.ByteString getHolecards();

      // optional bytes maxCards = 6;
      /**
       * <code>optional bytes maxCards = 6;</code>
       *
       * <pre>
       *最大牌组合
       * </pre>
       */
      boolean hasMaxCards();
      /**
       * <code>optional bytes maxCards = 6;</code>
       *
       * <pre>
       *最大牌组合
       * </pre>
       */
      com.google.protobuf.ByteString getMaxCards();

      // required bool won = 7;
      /**
       * <code>required bool won = 7;</code>
       *
       * <pre>
       *是否获胜(第一名)
       * </pre>
       */
      boolean hasWon();
      /**
       * <code>required bool won = 7;</code>
       *
       * <pre>
       *是否获胜(第一名)
       * </pre>
       */
      boolean getWon();

      // required int32 gainTotal = 8;
      /**
       * <code>required int32 gainTotal = 8;</code>
       *
       * <pre>
       *赢取金额(未减注额)
       * </pre>
       */
      boolean hasGainTotal();
      /**
       * <code>required int32 gainTotal = 8;</code>
       *
       * <pre>
       *赢取金额(未减注额)
       * </pre>
       */
      int getGainTotal();
    }
    /**
     * Protobuf type {@code ResultProto.Winner}
     */
    public static final class Winner extends
        com.google.protobuf.GeneratedMessage
        implements WinnerOrBuilder {
      // Use Winner.newBuilder() to construct.
      private Winner(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Winner(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Winner defaultInstance;
      public static Winner getDefaultInstance() {
        return defaultInstance;
      }

      public Winner getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Winner(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                playerId_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                seat_ = input.readInt32();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                title_ = input.readBytes();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                type_ = input.readInt32();
                break;
              }
              case 42: {
                bitField0_ |= 0x00000010;
                holecards_ = input.readBytes();
                break;
              }
              case 50: {
                bitField0_ |= 0x00000020;
                maxCards_ = input.readBytes();
                break;
              }
              case 56: {
                bitField0_ |= 0x00000040;
                won_ = input.readBool();
                break;
              }
              case 64: {
                bitField0_ |= 0x00000080;
                gainTotal_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ResultPro.internal_static_ResultProto_Winner_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ResultPro.internal_static_ResultProto_Winner_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ResultPro.ResultProto.Winner.class, ResultPro.ResultProto.Winner.Builder.class);
      }

      public static com.google.protobuf.Parser<Winner> PARSER =
          new com.google.protobuf.AbstractParser<Winner>() {
        public Winner parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Winner(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Winner> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required int32 playerId = 1;
      public static final int PLAYERID_FIELD_NUMBER = 1;
      private int playerId_;
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }

      // required int32 seat = 2;
      public static final int SEAT_FIELD_NUMBER = 2;
      private int seat_;
      /**
       * <code>required int32 seat = 2;</code>
       *
       * <pre>
       *座号
       * </pre>
       */
      public boolean hasSeat() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 seat = 2;</code>
       *
       * <pre>
       *座号
       * </pre>
       */
      public int getSeat() {
        return seat_;
      }

      // optional string title = 3;
      public static final int TITLE_FIELD_NUMBER = 3;
      private java.lang.Object title_;
      /**
       * <code>optional string title = 3;</code>
       *
       * <pre>
       *牌型名称
       * </pre>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string title = 3;</code>
       *
       * <pre>
       *牌型名称
       * </pre>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string title = 3;</code>
       *
       * <pre>
       *牌型名称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional int32 type = 4;
      public static final int TYPE_FIELD_NUMBER = 4;
      private int type_;
      /**
       * <code>optional int32 type = 4;</code>
       *
       * <pre>
       *牌型
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 type = 4;</code>
       *
       * <pre>
       *牌型
       * </pre>
       */
      public int getType() {
        return type_;
      }

      // optional bytes holecards = 5;
      public static final int HOLECARDS_FIELD_NUMBER = 5;
      private com.google.protobuf.ByteString holecards_;
      /**
       * <code>optional bytes holecards = 5;</code>
       */
      public boolean hasHolecards() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes holecards = 5;</code>
       */
      public com.google.protobuf.ByteString getHolecards() {
        return holecards_;
      }

      // optional bytes maxCards = 6;
      public static final int MAXCARDS_FIELD_NUMBER = 6;
      private com.google.protobuf.ByteString maxCards_;
      /**
       * <code>optional bytes maxCards = 6;</code>
       *
       * <pre>
       *最大牌组合
       * </pre>
       */
      public boolean hasMaxCards() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes maxCards = 6;</code>
       *
       * <pre>
       *最大牌组合
       * </pre>
       */
      public com.google.protobuf.ByteString getMaxCards() {
        return maxCards_;
      }

      // required bool won = 7;
      public static final int WON_FIELD_NUMBER = 7;
      private boolean won_;
      /**
       * <code>required bool won = 7;</code>
       *
       * <pre>
       *是否获胜(第一名)
       * </pre>
       */
      public boolean hasWon() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required bool won = 7;</code>
       *
       * <pre>
       *是否获胜(第一名)
       * </pre>
       */
      public boolean getWon() {
        return won_;
      }

      // required int32 gainTotal = 8;
      public static final int GAINTOTAL_FIELD_NUMBER = 8;
      private int gainTotal_;
      /**
       * <code>required int32 gainTotal = 8;</code>
       *
       * <pre>
       *赢取金额(未减注额)
       * </pre>
       */
      public boolean hasGainTotal() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int32 gainTotal = 8;</code>
       *
       * <pre>
       *赢取金额(未减注额)
       * </pre>
       */
      public int getGainTotal() {
        return gainTotal_;
      }

      private void initFields() {
        playerId_ = 0;
        seat_ = 0;
        title_ = "";
        type_ = 0;
        holecards_ = com.google.protobuf.ByteString.EMPTY;
        maxCards_ = com.google.protobuf.ByteString.EMPTY;
        won_ = false;
        gainTotal_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasPlayerId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasSeat()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasWon()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasGainTotal()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, playerId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, seat_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getTitleBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeInt32(4, type_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeBytes(5, holecards_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeBytes(6, maxCards_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          output.writeBool(7, won_);
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          output.writeInt32(8, gainTotal_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, playerId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, seat_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getTitleBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, type_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(5, holecards_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(6, maxCards_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(7, won_);
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(8, gainTotal_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static ResultPro.ResultProto.Winner parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ResultPro.ResultProto.Winner parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ResultPro.ResultProto.Winner parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ResultPro.ResultProto.Winner parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ResultPro.ResultProto.Winner parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static ResultPro.ResultProto.Winner parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static ResultPro.ResultProto.Winner parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static ResultPro.ResultProto.Winner parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static ResultPro.ResultProto.Winner parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static ResultPro.ResultProto.Winner parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(ResultPro.ResultProto.Winner prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ResultProto.Winner}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements ResultPro.ResultProto.WinnerOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ResultPro.internal_static_ResultProto_Winner_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ResultPro.internal_static_ResultProto_Winner_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ResultPro.ResultProto.Winner.class, ResultPro.ResultProto.Winner.Builder.class);
        }

        // Construct using ResultPro.ResultProto.Winner.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          playerId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          seat_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          title_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          type_ = 0;
          bitField0_ = (bitField0_ & ~0x00000008);
          holecards_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000010);
          maxCards_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000020);
          won_ = false;
          bitField0_ = (bitField0_ & ~0x00000040);
          gainTotal_ = 0;
          bitField0_ = (bitField0_ & ~0x00000080);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ResultPro.internal_static_ResultProto_Winner_descriptor;
        }

        public ResultPro.ResultProto.Winner getDefaultInstanceForType() {
          return ResultPro.ResultProto.Winner.getDefaultInstance();
        }

        public ResultPro.ResultProto.Winner build() {
          ResultPro.ResultProto.Winner result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public ResultPro.ResultProto.Winner buildPartial() {
          ResultPro.ResultProto.Winner result = new ResultPro.ResultProto.Winner(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.playerId_ = playerId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.seat_ = seat_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.title_ = title_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.holecards_ = holecards_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.maxCards_ = maxCards_;
          if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
            to_bitField0_ |= 0x00000040;
          }
          result.won_ = won_;
          if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
            to_bitField0_ |= 0x00000080;
          }
          result.gainTotal_ = gainTotal_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ResultPro.ResultProto.Winner) {
            return mergeFrom((ResultPro.ResultProto.Winner)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ResultPro.ResultProto.Winner other) {
          if (other == ResultPro.ResultProto.Winner.getDefaultInstance()) return this;
          if (other.hasPlayerId()) {
            setPlayerId(other.getPlayerId());
          }
          if (other.hasSeat()) {
            setSeat(other.getSeat());
          }
          if (other.hasTitle()) {
            bitField0_ |= 0x00000004;
            title_ = other.title_;
            onChanged();
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          if (other.hasHolecards()) {
            setHolecards(other.getHolecards());
          }
          if (other.hasMaxCards()) {
            setMaxCards(other.getMaxCards());
          }
          if (other.hasWon()) {
            setWon(other.getWon());
          }
          if (other.hasGainTotal()) {
            setGainTotal(other.getGainTotal());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasPlayerId()) {
            
            return false;
          }
          if (!hasSeat()) {
            
            return false;
          }
          if (!hasWon()) {
            
            return false;
          }
          if (!hasGainTotal()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ResultPro.ResultProto.Winner parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ResultPro.ResultProto.Winner) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required int32 playerId = 1;
        private int playerId_ ;
        /**
         * <code>required int32 playerId = 1;</code>
         */
        public boolean hasPlayerId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 playerId = 1;</code>
         */
        public int getPlayerId() {
          return playerId_;
        }
        /**
         * <code>required int32 playerId = 1;</code>
         */
        public Builder setPlayerId(int value) {
          bitField0_ |= 0x00000001;
          playerId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 playerId = 1;</code>
         */
        public Builder clearPlayerId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          playerId_ = 0;
          onChanged();
          return this;
        }

        // required int32 seat = 2;
        private int seat_ ;
        /**
         * <code>required int32 seat = 2;</code>
         *
         * <pre>
         *座号
         * </pre>
         */
        public boolean hasSeat() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 seat = 2;</code>
         *
         * <pre>
         *座号
         * </pre>
         */
        public int getSeat() {
          return seat_;
        }
        /**
         * <code>required int32 seat = 2;</code>
         *
         * <pre>
         *座号
         * </pre>
         */
        public Builder setSeat(int value) {
          bitField0_ |= 0x00000002;
          seat_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 seat = 2;</code>
         *
         * <pre>
         *座号
         * </pre>
         */
        public Builder clearSeat() {
          bitField0_ = (bitField0_ & ~0x00000002);
          seat_ = 0;
          onChanged();
          return this;
        }

        // optional string title = 3;
        private java.lang.Object title_ = "";
        /**
         * <code>optional string title = 3;</code>
         *
         * <pre>
         *牌型名称
         * </pre>
         */
        public boolean hasTitle() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string title = 3;</code>
         *
         * <pre>
         *牌型名称
         * </pre>
         */
        public java.lang.String getTitle() {
          java.lang.Object ref = title_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            title_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string title = 3;</code>
         *
         * <pre>
         *牌型名称
         * </pre>
         */
        public com.google.protobuf.ByteString
            getTitleBytes() {
          java.lang.Object ref = title_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            title_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string title = 3;</code>
         *
         * <pre>
         *牌型名称
         * </pre>
         */
        public Builder setTitle(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          title_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string title = 3;</code>
         *
         * <pre>
         *牌型名称
         * </pre>
         */
        public Builder clearTitle() {
          bitField0_ = (bitField0_ & ~0x00000004);
          title_ = getDefaultInstance().getTitle();
          onChanged();
          return this;
        }
        /**
         * <code>optional string title = 3;</code>
         *
         * <pre>
         *牌型名称
         * </pre>
         */
        public Builder setTitleBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          title_ = value;
          onChanged();
          return this;
        }

        // optional int32 type = 4;
        private int type_ ;
        /**
         * <code>optional int32 type = 4;</code>
         *
         * <pre>
         *牌型
         * </pre>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional int32 type = 4;</code>
         *
         * <pre>
         *牌型
         * </pre>
         */
        public int getType() {
          return type_;
        }
        /**
         * <code>optional int32 type = 4;</code>
         *
         * <pre>
         *牌型
         * </pre>
         */
        public Builder setType(int value) {
          bitField0_ |= 0x00000008;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 type = 4;</code>
         *
         * <pre>
         *牌型
         * </pre>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000008);
          type_ = 0;
          onChanged();
          return this;
        }

        // optional bytes holecards = 5;
        private com.google.protobuf.ByteString holecards_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes holecards = 5;</code>
         */
        public boolean hasHolecards() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional bytes holecards = 5;</code>
         */
        public com.google.protobuf.ByteString getHolecards() {
          return holecards_;
        }
        /**
         * <code>optional bytes holecards = 5;</code>
         */
        public Builder setHolecards(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
          holecards_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes holecards = 5;</code>
         */
        public Builder clearHolecards() {
          bitField0_ = (bitField0_ & ~0x00000010);
          holecards_ = getDefaultInstance().getHolecards();
          onChanged();
          return this;
        }

        // optional bytes maxCards = 6;
        private com.google.protobuf.ByteString maxCards_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes maxCards = 6;</code>
         *
         * <pre>
         *最大牌组合
         * </pre>
         */
        public boolean hasMaxCards() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional bytes maxCards = 6;</code>
         *
         * <pre>
         *最大牌组合
         * </pre>
         */
        public com.google.protobuf.ByteString getMaxCards() {
          return maxCards_;
        }
        /**
         * <code>optional bytes maxCards = 6;</code>
         *
         * <pre>
         *最大牌组合
         * </pre>
         */
        public Builder setMaxCards(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
          maxCards_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes maxCards = 6;</code>
         *
         * <pre>
         *最大牌组合
         * </pre>
         */
        public Builder clearMaxCards() {
          bitField0_ = (bitField0_ & ~0x00000020);
          maxCards_ = getDefaultInstance().getMaxCards();
          onChanged();
          return this;
        }

        // required bool won = 7;
        private boolean won_ ;
        /**
         * <code>required bool won = 7;</code>
         *
         * <pre>
         *是否获胜(第一名)
         * </pre>
         */
        public boolean hasWon() {
          return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>required bool won = 7;</code>
         *
         * <pre>
         *是否获胜(第一名)
         * </pre>
         */
        public boolean getWon() {
          return won_;
        }
        /**
         * <code>required bool won = 7;</code>
         *
         * <pre>
         *是否获胜(第一名)
         * </pre>
         */
        public Builder setWon(boolean value) {
          bitField0_ |= 0x00000040;
          won_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bool won = 7;</code>
         *
         * <pre>
         *是否获胜(第一名)
         * </pre>
         */
        public Builder clearWon() {
          bitField0_ = (bitField0_ & ~0x00000040);
          won_ = false;
          onChanged();
          return this;
        }

        // required int32 gainTotal = 8;
        private int gainTotal_ ;
        /**
         * <code>required int32 gainTotal = 8;</code>
         *
         * <pre>
         *赢取金额(未减注额)
         * </pre>
         */
        public boolean hasGainTotal() {
          return ((bitField0_ & 0x00000080) == 0x00000080);
        }
        /**
         * <code>required int32 gainTotal = 8;</code>
         *
         * <pre>
         *赢取金额(未减注额)
         * </pre>
         */
        public int getGainTotal() {
          return gainTotal_;
        }
        /**
         * <code>required int32 gainTotal = 8;</code>
         *
         * <pre>
         *赢取金额(未减注额)
         * </pre>
         */
        public Builder setGainTotal(int value) {
          bitField0_ |= 0x00000080;
          gainTotal_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 gainTotal = 8;</code>
         *
         * <pre>
         *赢取金额(未减注额)
         * </pre>
         */
        public Builder clearGainTotal() {
          bitField0_ = (bitField0_ & ~0x00000080);
          gainTotal_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ResultProto.Winner)
      }

      static {
        defaultInstance = new Winner(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:ResultProto.Winner)
    }

    // repeated .ResultProto.Winner winnerList = 1;
    public static final int WINNERLIST_FIELD_NUMBER = 1;
    private java.util.List<ResultPro.ResultProto.Winner> winnerList_;
    /**
     * <code>repeated .ResultProto.Winner winnerList = 1;</code>
     */
    public java.util.List<ResultPro.ResultProto.Winner> getWinnerListList() {
      return winnerList_;
    }
    /**
     * <code>repeated .ResultProto.Winner winnerList = 1;</code>
     */
    public java.util.List<? extends ResultPro.ResultProto.WinnerOrBuilder> 
        getWinnerListOrBuilderList() {
      return winnerList_;
    }
    /**
     * <code>repeated .ResultProto.Winner winnerList = 1;</code>
     */
    public int getWinnerListCount() {
      return winnerList_.size();
    }
    /**
     * <code>repeated .ResultProto.Winner winnerList = 1;</code>
     */
    public ResultPro.ResultProto.Winner getWinnerList(int index) {
      return winnerList_.get(index);
    }
    /**
     * <code>repeated .ResultProto.Winner winnerList = 1;</code>
     */
    public ResultPro.ResultProto.WinnerOrBuilder getWinnerListOrBuilder(
        int index) {
      return winnerList_.get(index);
    }

    private void initFields() {
      winnerList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getWinnerListCount(); i++) {
        if (!getWinnerList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < winnerList_.size(); i++) {
        output.writeMessage(1, winnerList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < winnerList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, winnerList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ResultPro.ResultProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResultPro.ResultProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResultPro.ResultProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResultPro.ResultProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResultPro.ResultProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ResultPro.ResultProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ResultPro.ResultProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ResultPro.ResultProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ResultPro.ResultProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ResultPro.ResultProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ResultPro.ResultProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResultProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ResultPro.ResultProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ResultPro.internal_static_ResultProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ResultPro.internal_static_ResultProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ResultPro.ResultProto.class, ResultPro.ResultProto.Builder.class);
      }

      // Construct using ResultPro.ResultProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getWinnerListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (winnerListBuilder_ == null) {
          winnerList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          winnerListBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ResultPro.internal_static_ResultProto_descriptor;
      }

      public ResultPro.ResultProto getDefaultInstanceForType() {
        return ResultPro.ResultProto.getDefaultInstance();
      }

      public ResultPro.ResultProto build() {
        ResultPro.ResultProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ResultPro.ResultProto buildPartial() {
        ResultPro.ResultProto result = new ResultPro.ResultProto(this);
        int from_bitField0_ = bitField0_;
        if (winnerListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            winnerList_ = java.util.Collections.unmodifiableList(winnerList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.winnerList_ = winnerList_;
        } else {
          result.winnerList_ = winnerListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ResultPro.ResultProto) {
          return mergeFrom((ResultPro.ResultProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ResultPro.ResultProto other) {
        if (other == ResultPro.ResultProto.getDefaultInstance()) return this;
        if (winnerListBuilder_ == null) {
          if (!other.winnerList_.isEmpty()) {
            if (winnerList_.isEmpty()) {
              winnerList_ = other.winnerList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureWinnerListIsMutable();
              winnerList_.addAll(other.winnerList_);
            }
            onChanged();
          }
        } else {
          if (!other.winnerList_.isEmpty()) {
            if (winnerListBuilder_.isEmpty()) {
              winnerListBuilder_.dispose();
              winnerListBuilder_ = null;
              winnerList_ = other.winnerList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              winnerListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getWinnerListFieldBuilder() : null;
            } else {
              winnerListBuilder_.addAllMessages(other.winnerList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getWinnerListCount(); i++) {
          if (!getWinnerList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ResultPro.ResultProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ResultPro.ResultProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .ResultProto.Winner winnerList = 1;
      private java.util.List<ResultPro.ResultProto.Winner> winnerList_ =
        java.util.Collections.emptyList();
      private void ensureWinnerListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          winnerList_ = new java.util.ArrayList<ResultPro.ResultProto.Winner>(winnerList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ResultPro.ResultProto.Winner, ResultPro.ResultProto.Winner.Builder, ResultPro.ResultProto.WinnerOrBuilder> winnerListBuilder_;

      /**
       * <code>repeated .ResultProto.Winner winnerList = 1;</code>
       */
      public java.util.List<ResultPro.ResultProto.Winner> getWinnerListList() {
        if (winnerListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(winnerList_);
        } else {
          return winnerListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ResultProto.Winner winnerList = 1;</code>
       */
      public int getWinnerListCount() {
        if (winnerListBuilder_ == null) {
          return winnerList_.size();
        } else {
          return winnerListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ResultProto.Winner winnerList = 1;</code>
       */
      public ResultPro.ResultProto.Winner getWinnerList(int index) {
        if (winnerListBuilder_ == null) {
          return winnerList_.get(index);
        } else {
          return winnerListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ResultProto.Winner winnerList = 1;</code>
       */
      public Builder setWinnerList(
          int index, ResultPro.ResultProto.Winner value) {
        if (winnerListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWinnerListIsMutable();
          winnerList_.set(index, value);
          onChanged();
        } else {
          winnerListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ResultProto.Winner winnerList = 1;</code>
       */
      public Builder setWinnerList(
          int index, ResultPro.ResultProto.Winner.Builder builderForValue) {
        if (winnerListBuilder_ == null) {
          ensureWinnerListIsMutable();
          winnerList_.set(index, builderForValue.build());
          onChanged();
        } else {
          winnerListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ResultProto.Winner winnerList = 1;</code>
       */
      public Builder addWinnerList(ResultPro.ResultProto.Winner value) {
        if (winnerListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWinnerListIsMutable();
          winnerList_.add(value);
          onChanged();
        } else {
          winnerListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ResultProto.Winner winnerList = 1;</code>
       */
      public Builder addWinnerList(
          int index, ResultPro.ResultProto.Winner value) {
        if (winnerListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWinnerListIsMutable();
          winnerList_.add(index, value);
          onChanged();
        } else {
          winnerListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ResultProto.Winner winnerList = 1;</code>
       */
      public Builder addWinnerList(
          ResultPro.ResultProto.Winner.Builder builderForValue) {
        if (winnerListBuilder_ == null) {
          ensureWinnerListIsMutable();
          winnerList_.add(builderForValue.build());
          onChanged();
        } else {
          winnerListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ResultProto.Winner winnerList = 1;</code>
       */
      public Builder addWinnerList(
          int index, ResultPro.ResultProto.Winner.Builder builderForValue) {
        if (winnerListBuilder_ == null) {
          ensureWinnerListIsMutable();
          winnerList_.add(index, builderForValue.build());
          onChanged();
        } else {
          winnerListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ResultProto.Winner winnerList = 1;</code>
       */
      public Builder addAllWinnerList(
          java.lang.Iterable<? extends ResultPro.ResultProto.Winner> values) {
        if (winnerListBuilder_ == null) {
          ensureWinnerListIsMutable();
          super.addAll(values, winnerList_);
          onChanged();
        } else {
          winnerListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ResultProto.Winner winnerList = 1;</code>
       */
      public Builder clearWinnerList() {
        if (winnerListBuilder_ == null) {
          winnerList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          winnerListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ResultProto.Winner winnerList = 1;</code>
       */
      public Builder removeWinnerList(int index) {
        if (winnerListBuilder_ == null) {
          ensureWinnerListIsMutable();
          winnerList_.remove(index);
          onChanged();
        } else {
          winnerListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ResultProto.Winner winnerList = 1;</code>
       */
      public ResultPro.ResultProto.Winner.Builder getWinnerListBuilder(
          int index) {
        return getWinnerListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ResultProto.Winner winnerList = 1;</code>
       */
      public ResultPro.ResultProto.WinnerOrBuilder getWinnerListOrBuilder(
          int index) {
        if (winnerListBuilder_ == null) {
          return winnerList_.get(index);  } else {
          return winnerListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ResultProto.Winner winnerList = 1;</code>
       */
      public java.util.List<? extends ResultPro.ResultProto.WinnerOrBuilder> 
           getWinnerListOrBuilderList() {
        if (winnerListBuilder_ != null) {
          return winnerListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(winnerList_);
        }
      }
      /**
       * <code>repeated .ResultProto.Winner winnerList = 1;</code>
       */
      public ResultPro.ResultProto.Winner.Builder addWinnerListBuilder() {
        return getWinnerListFieldBuilder().addBuilder(
            ResultPro.ResultProto.Winner.getDefaultInstance());
      }
      /**
       * <code>repeated .ResultProto.Winner winnerList = 1;</code>
       */
      public ResultPro.ResultProto.Winner.Builder addWinnerListBuilder(
          int index) {
        return getWinnerListFieldBuilder().addBuilder(
            index, ResultPro.ResultProto.Winner.getDefaultInstance());
      }
      /**
       * <code>repeated .ResultProto.Winner winnerList = 1;</code>
       */
      public java.util.List<ResultPro.ResultProto.Winner.Builder> 
           getWinnerListBuilderList() {
        return getWinnerListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ResultPro.ResultProto.Winner, ResultPro.ResultProto.Winner.Builder, ResultPro.ResultProto.WinnerOrBuilder> 
          getWinnerListFieldBuilder() {
        if (winnerListBuilder_ == null) {
          winnerListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ResultPro.ResultProto.Winner, ResultPro.ResultProto.Winner.Builder, ResultPro.ResultProto.WinnerOrBuilder>(
                  winnerList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          winnerList_ = null;
        }
        return winnerListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ResultProto)
    }

    static {
      defaultInstance = new ResultProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ResultProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ResultProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResultProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ResultProto_Winner_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResultProto_Winner_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ResultPro.proto\"\303\001\n\013ResultProto\022\'\n\nwin" +
      "nerList\030\001 \003(\0132\023.ResultProto.Winner\032\212\001\n\006W" +
      "inner\022\020\n\010playerId\030\001 \002(\005\022\014\n\004seat\030\002 \002(\005\022\r\n" +
      "\005title\030\003 \001(\t\022\014\n\004type\030\004 \001(\005\022\021\n\tholecards\030" +
      "\005 \001(\014\022\020\n\010maxCards\030\006 \001(\014\022\013\n\003won\030\007 \002(\010\022\021\n\t" +
      "gainTotal\030\010 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ResultProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ResultProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ResultProto_descriptor,
              new java.lang.String[] { "WinnerList", });
          internal_static_ResultProto_Winner_descriptor =
            internal_static_ResultProto_descriptor.getNestedTypes().get(0);
          internal_static_ResultProto_Winner_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ResultProto_Winner_descriptor,
              new java.lang.String[] { "PlayerId", "Seat", "Title", "Type", "Holecards", "MaxCards", "Won", "GainTotal", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
