package com.lingzerg.gamecenter.proto;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ValidationPro.proto

public final class ValidationPro {
  private ValidationPro() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ValidationProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string token = 1;
    /**
     * <code>required string token = 1;</code>
     */
    boolean hasToken();
    /**
     * <code>required string token = 1;</code>
     */
    java.lang.String getToken();
    /**
     * <code>required string token = 1;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    // required int32 roomType = 2;
    /**
     * <code>required int32 roomType = 2;</code>
     *
     * <pre>
     *1.普通赛.2.淘汰赛.
     * </pre>
     */
    boolean hasRoomType();
    /**
     * <code>required int32 roomType = 2;</code>
     *
     * <pre>
     *1.普通赛.2.淘汰赛.
     * </pre>
     */
    int getRoomType();

    // required int32 roomId = 3;
    /**
     * <code>required int32 roomId = 3;</code>
     */
    boolean hasRoomId();
    /**
     * <code>required int32 roomId = 3;</code>
     */
    int getRoomId();

    // required bool isSpectator = 4;
    /**
     * <code>required bool isSpectator = 4;</code>
     */
    boolean hasIsSpectator();
    /**
     * <code>required bool isSpectator = 4;</code>
     */
    boolean getIsSpectator();
  }
  /**
   * Protobuf type {@code ValidationProto}
   */
  public static final class ValidationProto extends
      com.google.protobuf.GeneratedMessage
      implements ValidationProtoOrBuilder {
    // Use ValidationProto.newBuilder() to construct.
    private ValidationProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ValidationProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ValidationProto defaultInstance;
    public static ValidationProto getDefaultInstance() {
      return defaultInstance;
    }

    public ValidationProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ValidationProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              token_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              roomType_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              roomId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              isSpectator_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ValidationPro.internal_static_ValidationProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ValidationPro.internal_static_ValidationProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ValidationPro.ValidationProto.class, ValidationPro.ValidationProto.Builder.class);
    }

    public static com.google.protobuf.Parser<ValidationProto> PARSER =
        new com.google.protobuf.AbstractParser<ValidationProto>() {
      public ValidationProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ValidationProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ValidationProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string token = 1;
    public static final int TOKEN_FIELD_NUMBER = 1;
    private java.lang.Object token_;
    /**
     * <code>required string token = 1;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string token = 1;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string token = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 roomType = 2;
    public static final int ROOMTYPE_FIELD_NUMBER = 2;
    private int roomType_;
    /**
     * <code>required int32 roomType = 2;</code>
     *
     * <pre>
     *1.普通赛.2.淘汰赛.
     * </pre>
     */
    public boolean hasRoomType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 roomType = 2;</code>
     *
     * <pre>
     *1.普通赛.2.淘汰赛.
     * </pre>
     */
    public int getRoomType() {
      return roomType_;
    }

    // required int32 roomId = 3;
    public static final int ROOMID_FIELD_NUMBER = 3;
    private int roomId_;
    /**
     * <code>required int32 roomId = 3;</code>
     */
    public boolean hasRoomId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 roomId = 3;</code>
     */
    public int getRoomId() {
      return roomId_;
    }

    // required bool isSpectator = 4;
    public static final int ISSPECTATOR_FIELD_NUMBER = 4;
    private boolean isSpectator_;
    /**
     * <code>required bool isSpectator = 4;</code>
     */
    public boolean hasIsSpectator() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bool isSpectator = 4;</code>
     */
    public boolean getIsSpectator() {
      return isSpectator_;
    }

    private void initFields() {
      token_ = "";
      roomType_ = 0;
      roomId_ = 0;
      isSpectator_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRoomType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRoomId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsSpectator()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTokenBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, roomType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, roomId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, isSpectator_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTokenBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, roomType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, roomId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isSpectator_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ValidationPro.ValidationProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ValidationPro.ValidationProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ValidationPro.ValidationProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ValidationPro.ValidationProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ValidationPro.ValidationProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ValidationPro.ValidationProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ValidationPro.ValidationProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ValidationPro.ValidationProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ValidationPro.ValidationProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ValidationPro.ValidationProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ValidationPro.ValidationProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ValidationProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ValidationPro.ValidationProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ValidationPro.internal_static_ValidationProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ValidationPro.internal_static_ValidationProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ValidationPro.ValidationProto.class, ValidationPro.ValidationProto.Builder.class);
      }

      // Construct using ValidationPro.ValidationProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        roomType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        roomId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        isSpectator_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ValidationPro.internal_static_ValidationProto_descriptor;
      }

      public ValidationPro.ValidationProto getDefaultInstanceForType() {
        return ValidationPro.ValidationProto.getDefaultInstance();
      }

      public ValidationPro.ValidationProto build() {
        ValidationPro.ValidationProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ValidationPro.ValidationProto buildPartial() {
        ValidationPro.ValidationProto result = new ValidationPro.ValidationProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.roomType_ = roomType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.roomId_ = roomId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.isSpectator_ = isSpectator_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ValidationPro.ValidationProto) {
          return mergeFrom((ValidationPro.ValidationProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ValidationPro.ValidationProto other) {
        if (other == ValidationPro.ValidationProto.getDefaultInstance()) return this;
        if (other.hasToken()) {
          bitField0_ |= 0x00000001;
          token_ = other.token_;
          onChanged();
        }
        if (other.hasRoomType()) {
          setRoomType(other.getRoomType());
        }
        if (other.hasRoomId()) {
          setRoomId(other.getRoomId());
        }
        if (other.hasIsSpectator()) {
          setIsSpectator(other.getIsSpectator());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasToken()) {
          
          return false;
        }
        if (!hasRoomType()) {
          
          return false;
        }
        if (!hasRoomId()) {
          
          return false;
        }
        if (!hasIsSpectator()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ValidationPro.ValidationProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ValidationPro.ValidationProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string token = 1;
      private java.lang.Object token_ = "";
      /**
       * <code>required string token = 1;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string token = 1;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string token = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string token = 1;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string token = 1;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>required string token = 1;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }

      // required int32 roomType = 2;
      private int roomType_ ;
      /**
       * <code>required int32 roomType = 2;</code>
       *
       * <pre>
       *1.普通赛.2.淘汰赛.
       * </pre>
       */
      public boolean hasRoomType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 roomType = 2;</code>
       *
       * <pre>
       *1.普通赛.2.淘汰赛.
       * </pre>
       */
      public int getRoomType() {
        return roomType_;
      }
      /**
       * <code>required int32 roomType = 2;</code>
       *
       * <pre>
       *1.普通赛.2.淘汰赛.
       * </pre>
       */
      public Builder setRoomType(int value) {
        bitField0_ |= 0x00000002;
        roomType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 roomType = 2;</code>
       *
       * <pre>
       *1.普通赛.2.淘汰赛.
       * </pre>
       */
      public Builder clearRoomType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        roomType_ = 0;
        onChanged();
        return this;
      }

      // required int32 roomId = 3;
      private int roomId_ ;
      /**
       * <code>required int32 roomId = 3;</code>
       */
      public boolean hasRoomId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 roomId = 3;</code>
       */
      public int getRoomId() {
        return roomId_;
      }
      /**
       * <code>required int32 roomId = 3;</code>
       */
      public Builder setRoomId(int value) {
        bitField0_ |= 0x00000004;
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 roomId = 3;</code>
       */
      public Builder clearRoomId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        roomId_ = 0;
        onChanged();
        return this;
      }

      // required bool isSpectator = 4;
      private boolean isSpectator_ ;
      /**
       * <code>required bool isSpectator = 4;</code>
       */
      public boolean hasIsSpectator() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bool isSpectator = 4;</code>
       */
      public boolean getIsSpectator() {
        return isSpectator_;
      }
      /**
       * <code>required bool isSpectator = 4;</code>
       */
      public Builder setIsSpectator(boolean value) {
        bitField0_ |= 0x00000008;
        isSpectator_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isSpectator = 4;</code>
       */
      public Builder clearIsSpectator() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isSpectator_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ValidationProto)
    }

    static {
      defaultInstance = new ValidationProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ValidationProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ValidationProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ValidationProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ValidationPro.proto\"W\n\017ValidationProto" +
      "\022\r\n\005token\030\001 \002(\t\022\020\n\010roomType\030\002 \002(\005\022\016\n\006roo" +
      "mId\030\003 \002(\005\022\023\n\013isSpectator\030\004 \002(\010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ValidationProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ValidationProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ValidationProto_descriptor,
              new java.lang.String[] { "Token", "RoomType", "RoomId", "IsSpectator", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
