package poker.proto;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoFactoryForCtrlCenter.proto

public final class ProtoFactoryForCtrlCenter {
  private ProtoFactoryForCtrlCenter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CCValidationProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string token = 1;
    /**
     * <code>required string token = 1;</code>
     */
    boolean hasToken();
    /**
     * <code>required string token = 1;</code>
     */
    java.lang.String getToken();
    /**
     * <code>required string token = 1;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code CCValidationProto}
   */
  public static final class CCValidationProto extends
      com.google.protobuf.GeneratedMessage
      implements CCValidationProtoOrBuilder {
    // Use CCValidationProto.newBuilder() to construct.
    private CCValidationProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CCValidationProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CCValidationProto defaultInstance;
    public static CCValidationProto getDefaultInstance() {
      return defaultInstance;
    }

    @Override
	public CCValidationProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CCValidationProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              token_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoFactoryForCtrlCenter.internal_static_CCValidationProto_descriptor;
    }

    @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoFactoryForCtrlCenter.internal_static_CCValidationProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoFactoryForCtrlCenter.CCValidationProto.class, ProtoFactoryForCtrlCenter.CCValidationProto.Builder.class);
    }

    public static com.google.protobuf.Parser<CCValidationProto> PARSER =
        new com.google.protobuf.AbstractParser<CCValidationProto>() {
      @Override
	public CCValidationProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CCValidationProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CCValidationProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string token = 1;
    public static final int TOKEN_FIELD_NUMBER = 1;
    private java.lang.Object token_;
    /**
     * <code>required string token = 1;</code>
     */
    @Override
	public boolean hasToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string token = 1;</code>
     */
    @Override
	public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string token = 1;</code>
     */
    @Override
	public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      token_ = "";
    }
    private byte memoizedIsInitialized = -1;
    @Override
	public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTokenBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    @Override
	public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTokenBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ProtoFactoryForCtrlCenter.CCValidationProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoFactoryForCtrlCenter.CCValidationProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoFactoryForCtrlCenter.CCValidationProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoFactoryForCtrlCenter.CCValidationProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoFactoryForCtrlCenter.CCValidationProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoFactoryForCtrlCenter.CCValidationProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ProtoFactoryForCtrlCenter.CCValidationProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ProtoFactoryForCtrlCenter.CCValidationProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ProtoFactoryForCtrlCenter.CCValidationProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoFactoryForCtrlCenter.CCValidationProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    @Override
	public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoFactoryForCtrlCenter.CCValidationProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
	public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CCValidationProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtoFactoryForCtrlCenter.CCValidationProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoFactoryForCtrlCenter.internal_static_CCValidationProto_descriptor;
      }

      @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoFactoryForCtrlCenter.internal_static_CCValidationProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoFactoryForCtrlCenter.CCValidationProto.class, ProtoFactoryForCtrlCenter.CCValidationProto.Builder.class);
      }

      // Construct using ProtoFactoryForCtrlCenter.CCValidationProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      @Override
	public Builder clear() {
        super.clear();
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
	public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      @Override
	public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoFactoryForCtrlCenter.internal_static_CCValidationProto_descriptor;
      }

      @Override
	public ProtoFactoryForCtrlCenter.CCValidationProto getDefaultInstanceForType() {
        return ProtoFactoryForCtrlCenter.CCValidationProto.getDefaultInstance();
      }

      @Override
	public ProtoFactoryForCtrlCenter.CCValidationProto build() {
        ProtoFactoryForCtrlCenter.CCValidationProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
	public ProtoFactoryForCtrlCenter.CCValidationProto buildPartial() {
        ProtoFactoryForCtrlCenter.CCValidationProto result = new ProtoFactoryForCtrlCenter.CCValidationProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.token_ = token_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoFactoryForCtrlCenter.CCValidationProto) {
          return mergeFrom((ProtoFactoryForCtrlCenter.CCValidationProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoFactoryForCtrlCenter.CCValidationProto other) {
        if (other == ProtoFactoryForCtrlCenter.CCValidationProto.getDefaultInstance()) return this;
        if (other.hasToken()) {
          bitField0_ |= 0x00000001;
          token_ = other.token_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      @Override
	public final boolean isInitialized() {
        if (!hasToken()) {
          
          return false;
        }
        return true;
      }

      @Override
	public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoFactoryForCtrlCenter.CCValidationProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoFactoryForCtrlCenter.CCValidationProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string token = 1;
      private java.lang.Object token_ = "";
      /**
       * <code>required string token = 1;</code>
       */
      @Override
	public boolean hasToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string token = 1;</code>
       */
      @Override
	public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string token = 1;</code>
       */
      @Override
	public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string token = 1;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string token = 1;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>required string token = 1;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CCValidationProto)
    }

    static {
      defaultInstance = new CCValidationProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CCValidationProto)
  }

  public interface CCPlayerStausProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 playerId = 1;
    /**
     * <code>required int32 playerId = 1;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>required int32 playerId = 1;</code>
     */
    int getPlayerId();

    // optional int32 status = 2;
    /**
     * <code>optional int32 status = 2;</code>
     *
     * <pre>
     *0.不存在，1.正常，2.断开
     * </pre>
     */
    boolean hasStatus();
    /**
     * <code>optional int32 status = 2;</code>
     *
     * <pre>
     *0.不存在，1.正常，2.断开
     * </pre>
     */
    int getStatus();
  }
  /**
   * Protobuf type {@code CCPlayerStausProto}
   */
  public static final class CCPlayerStausProto extends
      com.google.protobuf.GeneratedMessage
      implements CCPlayerStausProtoOrBuilder {
    // Use CCPlayerStausProto.newBuilder() to construct.
    private CCPlayerStausProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CCPlayerStausProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CCPlayerStausProto defaultInstance;
    public static CCPlayerStausProto getDefaultInstance() {
      return defaultInstance;
    }

    @Override
	public CCPlayerStausProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CCPlayerStausProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              status_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoFactoryForCtrlCenter.internal_static_CCPlayerStausProto_descriptor;
    }

    @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoFactoryForCtrlCenter.internal_static_CCPlayerStausProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoFactoryForCtrlCenter.CCPlayerStausProto.class, ProtoFactoryForCtrlCenter.CCPlayerStausProto.Builder.class);
    }

    public static com.google.protobuf.Parser<CCPlayerStausProto> PARSER =
        new com.google.protobuf.AbstractParser<CCPlayerStausProto>() {
      @Override
	public CCPlayerStausProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CCPlayerStausProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CCPlayerStausProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 playerId = 1;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private int playerId_;
    /**
     * <code>required int32 playerId = 1;</code>
     */
    @Override
	public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 playerId = 1;</code>
     */
    @Override
	public int getPlayerId() {
      return playerId_;
    }

    // optional int32 status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    /**
     * <code>optional int32 status = 2;</code>
     *
     * <pre>
     *0.不存在，1.正常，2.断开
     * </pre>
     */
    @Override
	public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 status = 2;</code>
     *
     * <pre>
     *0.不存在，1.正常，2.断开
     * </pre>
     */
    @Override
	public int getStatus() {
      return status_;
    }

    private void initFields() {
      playerId_ = 0;
      status_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    @Override
	public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, status_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    @Override
	public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ProtoFactoryForCtrlCenter.CCPlayerStausProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoFactoryForCtrlCenter.CCPlayerStausProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoFactoryForCtrlCenter.CCPlayerStausProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoFactoryForCtrlCenter.CCPlayerStausProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoFactoryForCtrlCenter.CCPlayerStausProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoFactoryForCtrlCenter.CCPlayerStausProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ProtoFactoryForCtrlCenter.CCPlayerStausProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ProtoFactoryForCtrlCenter.CCPlayerStausProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ProtoFactoryForCtrlCenter.CCPlayerStausProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoFactoryForCtrlCenter.CCPlayerStausProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    @Override
	public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoFactoryForCtrlCenter.CCPlayerStausProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
	public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CCPlayerStausProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtoFactoryForCtrlCenter.CCPlayerStausProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoFactoryForCtrlCenter.internal_static_CCPlayerStausProto_descriptor;
      }

      @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoFactoryForCtrlCenter.internal_static_CCPlayerStausProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoFactoryForCtrlCenter.CCPlayerStausProto.class, ProtoFactoryForCtrlCenter.CCPlayerStausProto.Builder.class);
      }

      // Construct using ProtoFactoryForCtrlCenter.CCPlayerStausProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      @Override
	public Builder clear() {
        super.clear();
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override
	public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      @Override
	public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoFactoryForCtrlCenter.internal_static_CCPlayerStausProto_descriptor;
      }

      @Override
	public ProtoFactoryForCtrlCenter.CCPlayerStausProto getDefaultInstanceForType() {
        return ProtoFactoryForCtrlCenter.CCPlayerStausProto.getDefaultInstance();
      }

      @Override
	public ProtoFactoryForCtrlCenter.CCPlayerStausProto build() {
        ProtoFactoryForCtrlCenter.CCPlayerStausProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
	public ProtoFactoryForCtrlCenter.CCPlayerStausProto buildPartial() {
        ProtoFactoryForCtrlCenter.CCPlayerStausProto result = new ProtoFactoryForCtrlCenter.CCPlayerStausProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoFactoryForCtrlCenter.CCPlayerStausProto) {
          return mergeFrom((ProtoFactoryForCtrlCenter.CCPlayerStausProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoFactoryForCtrlCenter.CCPlayerStausProto other) {
        if (other == ProtoFactoryForCtrlCenter.CCPlayerStausProto.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      @Override
	public final boolean isInitialized() {
        if (!hasPlayerId()) {
          
          return false;
        }
        return true;
      }

      @Override
	public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoFactoryForCtrlCenter.CCPlayerStausProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoFactoryForCtrlCenter.CCPlayerStausProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 playerId = 1;
      private int playerId_ ;
      /**
       * <code>required int32 playerId = 1;</code>
       */
      @Override
	public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 playerId = 1;</code>
       */
      @Override
	public int getPlayerId() {
        return playerId_;
      }
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 playerId = 1;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 status = 2;
      private int status_ ;
      /**
       * <code>optional int32 status = 2;</code>
       *
       * <pre>
       *0.不存在，1.正常，2.断开
       * </pre>
       */
      @Override
	public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 status = 2;</code>
       *
       * <pre>
       *0.不存在，1.正常，2.断开
       * </pre>
       */
      @Override
	public int getStatus() {
        return status_;
      }
      /**
       * <code>optional int32 status = 2;</code>
       *
       * <pre>
       *0.不存在，1.正常，2.断开
       * </pre>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 status = 2;</code>
       *
       * <pre>
       *0.不存在，1.正常，2.断开
       * </pre>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CCPlayerStausProto)
    }

    static {
      defaultInstance = new CCPlayerStausProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CCPlayerStausProto)
  }

  public interface CCPlayerStatusListProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .CCPlayerStausProto playerStatusList = 1;
    /**
     * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
     */
    java.util.List<ProtoFactoryForCtrlCenter.CCPlayerStausProto> 
        getPlayerStatusListList();
    /**
     * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
     */
    ProtoFactoryForCtrlCenter.CCPlayerStausProto getPlayerStatusList(int index);
    /**
     * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
     */
    int getPlayerStatusListCount();
    /**
     * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
     */
    java.util.List<? extends ProtoFactoryForCtrlCenter.CCPlayerStausProtoOrBuilder> 
        getPlayerStatusListOrBuilderList();
    /**
     * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
     */
    ProtoFactoryForCtrlCenter.CCPlayerStausProtoOrBuilder getPlayerStatusListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code CCPlayerStatusListProto}
   */
  public static final class CCPlayerStatusListProto extends
      com.google.protobuf.GeneratedMessage
      implements CCPlayerStatusListProtoOrBuilder {
    // Use CCPlayerStatusListProto.newBuilder() to construct.
    private CCPlayerStatusListProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CCPlayerStatusListProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CCPlayerStatusListProto defaultInstance;
    public static CCPlayerStatusListProto getDefaultInstance() {
      return defaultInstance;
    }

    @Override
	public CCPlayerStatusListProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CCPlayerStatusListProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                playerStatusList_ = new java.util.ArrayList<ProtoFactoryForCtrlCenter.CCPlayerStausProto>();
                mutable_bitField0_ |= 0x00000001;
              }
              playerStatusList_.add(input.readMessage(ProtoFactoryForCtrlCenter.CCPlayerStausProto.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          playerStatusList_ = java.util.Collections.unmodifiableList(playerStatusList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoFactoryForCtrlCenter.internal_static_CCPlayerStatusListProto_descriptor;
    }

    @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoFactoryForCtrlCenter.internal_static_CCPlayerStatusListProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoFactoryForCtrlCenter.CCPlayerStatusListProto.class, ProtoFactoryForCtrlCenter.CCPlayerStatusListProto.Builder.class);
    }

    public static com.google.protobuf.Parser<CCPlayerStatusListProto> PARSER =
        new com.google.protobuf.AbstractParser<CCPlayerStatusListProto>() {
      @Override
	public CCPlayerStatusListProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CCPlayerStatusListProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CCPlayerStatusListProto> getParserForType() {
      return PARSER;
    }

    // repeated .CCPlayerStausProto playerStatusList = 1;
    public static final int PLAYERSTATUSLIST_FIELD_NUMBER = 1;
    private java.util.List<ProtoFactoryForCtrlCenter.CCPlayerStausProto> playerStatusList_;
    /**
     * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
     */
    @Override
	public java.util.List<ProtoFactoryForCtrlCenter.CCPlayerStausProto> getPlayerStatusListList() {
      return playerStatusList_;
    }
    /**
     * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
     */
    @Override
	public java.util.List<? extends ProtoFactoryForCtrlCenter.CCPlayerStausProtoOrBuilder> 
        getPlayerStatusListOrBuilderList() {
      return playerStatusList_;
    }
    /**
     * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
     */
    @Override
	public int getPlayerStatusListCount() {
      return playerStatusList_.size();
    }
    /**
     * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
     */
    @Override
	public ProtoFactoryForCtrlCenter.CCPlayerStausProto getPlayerStatusList(int index) {
      return playerStatusList_.get(index);
    }
    /**
     * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
     */
    @Override
	public ProtoFactoryForCtrlCenter.CCPlayerStausProtoOrBuilder getPlayerStatusListOrBuilder(
        int index) {
      return playerStatusList_.get(index);
    }

    private void initFields() {
      playerStatusList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    @Override
	public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getPlayerStatusListCount(); i++) {
        if (!getPlayerStatusList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < playerStatusList_.size(); i++) {
        output.writeMessage(1, playerStatusList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    @Override
	public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < playerStatusList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, playerStatusList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ProtoFactoryForCtrlCenter.CCPlayerStatusListProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoFactoryForCtrlCenter.CCPlayerStatusListProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoFactoryForCtrlCenter.CCPlayerStatusListProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoFactoryForCtrlCenter.CCPlayerStatusListProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoFactoryForCtrlCenter.CCPlayerStatusListProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoFactoryForCtrlCenter.CCPlayerStatusListProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ProtoFactoryForCtrlCenter.CCPlayerStatusListProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ProtoFactoryForCtrlCenter.CCPlayerStatusListProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ProtoFactoryForCtrlCenter.CCPlayerStatusListProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoFactoryForCtrlCenter.CCPlayerStatusListProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    @Override
	public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoFactoryForCtrlCenter.CCPlayerStatusListProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
	public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CCPlayerStatusListProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtoFactoryForCtrlCenter.CCPlayerStatusListProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoFactoryForCtrlCenter.internal_static_CCPlayerStatusListProto_descriptor;
      }

      @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoFactoryForCtrlCenter.internal_static_CCPlayerStatusListProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoFactoryForCtrlCenter.CCPlayerStatusListProto.class, ProtoFactoryForCtrlCenter.CCPlayerStatusListProto.Builder.class);
      }

      // Construct using ProtoFactoryForCtrlCenter.CCPlayerStatusListProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPlayerStatusListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      @Override
	public Builder clear() {
        super.clear();
        if (playerStatusListBuilder_ == null) {
          playerStatusList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          playerStatusListBuilder_.clear();
        }
        return this;
      }

      @Override
	public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      @Override
	public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoFactoryForCtrlCenter.internal_static_CCPlayerStatusListProto_descriptor;
      }

      @Override
	public ProtoFactoryForCtrlCenter.CCPlayerStatusListProto getDefaultInstanceForType() {
        return ProtoFactoryForCtrlCenter.CCPlayerStatusListProto.getDefaultInstance();
      }

      @Override
	public ProtoFactoryForCtrlCenter.CCPlayerStatusListProto build() {
        ProtoFactoryForCtrlCenter.CCPlayerStatusListProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
	public ProtoFactoryForCtrlCenter.CCPlayerStatusListProto buildPartial() {
        ProtoFactoryForCtrlCenter.CCPlayerStatusListProto result = new ProtoFactoryForCtrlCenter.CCPlayerStatusListProto(this);
        int from_bitField0_ = bitField0_;
        if (playerStatusListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            playerStatusList_ = java.util.Collections.unmodifiableList(playerStatusList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.playerStatusList_ = playerStatusList_;
        } else {
          result.playerStatusList_ = playerStatusListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoFactoryForCtrlCenter.CCPlayerStatusListProto) {
          return mergeFrom((ProtoFactoryForCtrlCenter.CCPlayerStatusListProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoFactoryForCtrlCenter.CCPlayerStatusListProto other) {
        if (other == ProtoFactoryForCtrlCenter.CCPlayerStatusListProto.getDefaultInstance()) return this;
        if (playerStatusListBuilder_ == null) {
          if (!other.playerStatusList_.isEmpty()) {
            if (playerStatusList_.isEmpty()) {
              playerStatusList_ = other.playerStatusList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePlayerStatusListIsMutable();
              playerStatusList_.addAll(other.playerStatusList_);
            }
            onChanged();
          }
        } else {
          if (!other.playerStatusList_.isEmpty()) {
            if (playerStatusListBuilder_.isEmpty()) {
              playerStatusListBuilder_.dispose();
              playerStatusListBuilder_ = null;
              playerStatusList_ = other.playerStatusList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              playerStatusListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPlayerStatusListFieldBuilder() : null;
            } else {
              playerStatusListBuilder_.addAllMessages(other.playerStatusList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      @Override
	public final boolean isInitialized() {
        for (int i = 0; i < getPlayerStatusListCount(); i++) {
          if (!getPlayerStatusList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      @Override
	public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoFactoryForCtrlCenter.CCPlayerStatusListProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoFactoryForCtrlCenter.CCPlayerStatusListProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .CCPlayerStausProto playerStatusList = 1;
      private java.util.List<ProtoFactoryForCtrlCenter.CCPlayerStausProto> playerStatusList_ =
        java.util.Collections.emptyList();
      private void ensurePlayerStatusListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          playerStatusList_ = new java.util.ArrayList<ProtoFactoryForCtrlCenter.CCPlayerStausProto>(playerStatusList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ProtoFactoryForCtrlCenter.CCPlayerStausProto, ProtoFactoryForCtrlCenter.CCPlayerStausProto.Builder, ProtoFactoryForCtrlCenter.CCPlayerStausProtoOrBuilder> playerStatusListBuilder_;

      /**
       * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
       */
      @Override
	public java.util.List<ProtoFactoryForCtrlCenter.CCPlayerStausProto> getPlayerStatusListList() {
        if (playerStatusListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(playerStatusList_);
        } else {
          return playerStatusListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
       */
      @Override
	public int getPlayerStatusListCount() {
        if (playerStatusListBuilder_ == null) {
          return playerStatusList_.size();
        } else {
          return playerStatusListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
       */
      @Override
	public ProtoFactoryForCtrlCenter.CCPlayerStausProto getPlayerStatusList(int index) {
        if (playerStatusListBuilder_ == null) {
          return playerStatusList_.get(index);
        } else {
          return playerStatusListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
       */
      public Builder setPlayerStatusList(
          int index, ProtoFactoryForCtrlCenter.CCPlayerStausProto value) {
        if (playerStatusListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayerStatusListIsMutable();
          playerStatusList_.set(index, value);
          onChanged();
        } else {
          playerStatusListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
       */
      public Builder setPlayerStatusList(
          int index, ProtoFactoryForCtrlCenter.CCPlayerStausProto.Builder builderForValue) {
        if (playerStatusListBuilder_ == null) {
          ensurePlayerStatusListIsMutable();
          playerStatusList_.set(index, builderForValue.build());
          onChanged();
        } else {
          playerStatusListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
       */
      public Builder addPlayerStatusList(ProtoFactoryForCtrlCenter.CCPlayerStausProto value) {
        if (playerStatusListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayerStatusListIsMutable();
          playerStatusList_.add(value);
          onChanged();
        } else {
          playerStatusListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
       */
      public Builder addPlayerStatusList(
          int index, ProtoFactoryForCtrlCenter.CCPlayerStausProto value) {
        if (playerStatusListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayerStatusListIsMutable();
          playerStatusList_.add(index, value);
          onChanged();
        } else {
          playerStatusListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
       */
      public Builder addPlayerStatusList(
          ProtoFactoryForCtrlCenter.CCPlayerStausProto.Builder builderForValue) {
        if (playerStatusListBuilder_ == null) {
          ensurePlayerStatusListIsMutable();
          playerStatusList_.add(builderForValue.build());
          onChanged();
        } else {
          playerStatusListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
       */
      public Builder addPlayerStatusList(
          int index, ProtoFactoryForCtrlCenter.CCPlayerStausProto.Builder builderForValue) {
        if (playerStatusListBuilder_ == null) {
          ensurePlayerStatusListIsMutable();
          playerStatusList_.add(index, builderForValue.build());
          onChanged();
        } else {
          playerStatusListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
       */
      public Builder addAllPlayerStatusList(
          java.lang.Iterable<? extends ProtoFactoryForCtrlCenter.CCPlayerStausProto> values) {
        if (playerStatusListBuilder_ == null) {
          ensurePlayerStatusListIsMutable();
          super.addAll(values, playerStatusList_);
          onChanged();
        } else {
          playerStatusListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
       */
      public Builder clearPlayerStatusList() {
        if (playerStatusListBuilder_ == null) {
          playerStatusList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          playerStatusListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
       */
      public Builder removePlayerStatusList(int index) {
        if (playerStatusListBuilder_ == null) {
          ensurePlayerStatusListIsMutable();
          playerStatusList_.remove(index);
          onChanged();
        } else {
          playerStatusListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
       */
      public ProtoFactoryForCtrlCenter.CCPlayerStausProto.Builder getPlayerStatusListBuilder(
          int index) {
        return getPlayerStatusListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
       */
      @Override
	public ProtoFactoryForCtrlCenter.CCPlayerStausProtoOrBuilder getPlayerStatusListOrBuilder(
          int index) {
        if (playerStatusListBuilder_ == null) {
          return playerStatusList_.get(index);  } else {
          return playerStatusListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
       */
      @Override
	public java.util.List<? extends ProtoFactoryForCtrlCenter.CCPlayerStausProtoOrBuilder> 
           getPlayerStatusListOrBuilderList() {
        if (playerStatusListBuilder_ != null) {
          return playerStatusListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(playerStatusList_);
        }
      }
      /**
       * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
       */
      public ProtoFactoryForCtrlCenter.CCPlayerStausProto.Builder addPlayerStatusListBuilder() {
        return getPlayerStatusListFieldBuilder().addBuilder(
            ProtoFactoryForCtrlCenter.CCPlayerStausProto.getDefaultInstance());
      }
      /**
       * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
       */
      public ProtoFactoryForCtrlCenter.CCPlayerStausProto.Builder addPlayerStatusListBuilder(
          int index) {
        return getPlayerStatusListFieldBuilder().addBuilder(
            index, ProtoFactoryForCtrlCenter.CCPlayerStausProto.getDefaultInstance());
      }
      /**
       * <code>repeated .CCPlayerStausProto playerStatusList = 1;</code>
       */
      public java.util.List<ProtoFactoryForCtrlCenter.CCPlayerStausProto.Builder> 
           getPlayerStatusListBuilderList() {
        return getPlayerStatusListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ProtoFactoryForCtrlCenter.CCPlayerStausProto, ProtoFactoryForCtrlCenter.CCPlayerStausProto.Builder, ProtoFactoryForCtrlCenter.CCPlayerStausProtoOrBuilder> 
          getPlayerStatusListFieldBuilder() {
        if (playerStatusListBuilder_ == null) {
          playerStatusListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ProtoFactoryForCtrlCenter.CCPlayerStausProto, ProtoFactoryForCtrlCenter.CCPlayerStausProto.Builder, ProtoFactoryForCtrlCenter.CCPlayerStausProtoOrBuilder>(
                  playerStatusList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          playerStatusList_ = null;
        }
        return playerStatusListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:CCPlayerStatusListProto)
    }

    static {
      defaultInstance = new CCPlayerStatusListProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CCPlayerStatusListProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CCValidationProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CCValidationProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CCPlayerStausProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CCPlayerStausProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CCPlayerStatusListProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CCPlayerStatusListProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037ProtoFactoryForCtrlCenter.proto\"\"\n\021CCV" +
      "alidationProto\022\r\n\005token\030\001 \002(\t\"6\n\022CCPlaye" +
      "rStausProto\022\020\n\010playerId\030\001 \002(\005\022\016\n\006status\030" +
      "\002 \001(\005\"H\n\027CCPlayerStatusListProto\022-\n\020play" +
      "erStatusList\030\001 \003(\0132\023.CCPlayerStausProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        @Override
		public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CCValidationProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CCValidationProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CCValidationProto_descriptor,
              new java.lang.String[] { "Token", });
          internal_static_CCPlayerStausProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_CCPlayerStausProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CCPlayerStausProto_descriptor,
              new java.lang.String[] { "PlayerId", "Status", });
          internal_static_CCPlayerStatusListProto_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_CCPlayerStatusListProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CCPlayerStatusListProto_descriptor,
              new java.lang.String[] { "PlayerStatusList", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
